### ISSUE TITLE
Transfer custom activities repos to ParaguayEduca.

### ISSUE THREAD

**Issue by tchx84** [ParaguayEduca/os-builder#22]
All [these](https://github.com/ParaguayEduca/os-builder/blob/master/config/activitiesGit.sh#L203) custom activity forks must be hosted under ParaguayEduca github's.

**Comment by tchx84** [comment]
Please do.

**Comment by tchx84** [comment]
@Angatupyry is there any particular reason this hasn't been fixed? It should be as easy as transfering these repositories to ParaguayEduca github and update the urls in the script.

**Comment by Angatupyry** [comment]
Sorry, @tchx84 . The only reason was to test that this activities work, stay focused on that. That’s why this issue remained in a pending state.
