### ISSUE TITLE
Move package installation to "master" package.

### ISSUE THREAD

**Issue by tchx84** [ParaguayEduca/os-builder#23]
Instead of installing these packages [one by one](https://github.com/ParaguayEduca/os-builder/blob/master/config/install.sh#L7), create a "master" package, e.g. pyedu-dependencies, pyedu-packages, or whatever. And make that package require the packages you want installed.

This will help to manage already installed images in the future.

**Comment by Angatupyry** [comment]
The base of the metapackage is in the http://ppa.launchpad.net/crolon/activities/ubuntu/pool/main/p/pyedu/ repository.
This metapackage has the necessary dependencies to avoid one by one installation.
