### ISSUE TITLE
Move pyedudependencies package source files to ParaguayEduca github

### ISSUE THREAD

**Issue by tchx84** [ParaguayEduca/os-builder#36]

**Comment by Angatupyry** [comment]
Which specifically? Gcompris-qt, etoys, geogebra and tuxpaint?
These repositories
https://github.com/ParaguayEduca/geogebra-activity
https://github.com/ParaguayEduca/gcompris-activity
https://github.com/ParaguayEduca/etoys.activity
require those packages to be installed to work within Sugar.

**Comment by tchx84** [comment]
The pyedu-dependencies package source file, e.g. package debian directory with rules/control/etc files. That should be hosted under ParaguayEduca account as well.

Everything that is needed to build the image (and that is produced by Paraguay Educa team) should be hosted here.

**Comment by Angatupyry** [comment]
Done 
https://github.com/ParaguayEduca/pyedu-dependencies
