### ISSUE TITLE
Specify tag or commit when cloning activities

### ISSUE THREAD

**Issue by tchx84** [ParaguayEduca/os-builder#38]
When `git` cloning activities we must specify the version we want in our builds, this can be done with tags, commits or branches.

Most Sugar use tag for stable release releases, now, if you need a specific version from master (e.g. because it fixed some bug), then use the commit.

Just cloning from master, which a development branch is a dangerious practice.

**Comment by tchx84** [comment]
I still see other activities being cloned without a tag or commit. If there's no tag, then use the commit, as I explained before.

**Comment by Angatupyry** [comment]
Done.
